# Generated by Django 5.2.1 on 2025-05-20 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_nome', max_length=70)),
                ('phone', models.CharField(db_column='tx_fone', max_length=10)),
                ('email', models.CharField(db_column='tx_email', max_length=70)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('model', models.CharField(db_column='tx_modelo', max_length=20)),
                ('brand', models.CharField(db_column='tx_marca', max_length=20)),
                ('year', models.IntegerField(db_column='nb_ano')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('repair', models.CharField(db_column='tx_reparo', max_length=255)),
                ('cost', models.IntegerField(db_column='nb_custo')),
                ('client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.DO_NOTHING, to='oficina.client')),
                ('vehicle', models.ForeignKey(db_column='id_vehicle', on_delete=django.db.models.deletion.DO_NOTHING, to='oficina.vehicle')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
